### ISSUE TITLE
Error running "make provision configure"

### ISSUE THREAD

**Issue by chanduvkp** [request-yo-racks/infra#20]
I am getting error while running script "make provision configure"

**Error**
| => make provision configure
minikube-setup.sh: line 10: minikube: command not found
minikube-setup.sh: line 10: brew: command not found
make[1]: *** [minikube-start] Error 127
make: *** [minikube] Error 2

Issue Type
----------
Infra

Expected Behavior
-----------------
When i execute "make provision configure", kubernetes services should run

Current Behavior
----------------
Currently i am getting below error:

 => make provision configure
minikube-setup.sh: line 10: minikube: command not found
minikube-setup.sh: line 10: brew: command not found
make[1]: *** [minikube-start] Error 127
make: *** [minikube] Error 2

Possible Solution
-----------------

Steps to Reproduce (for bugs)
-----------------------------

1.
2.
3.
4.

Context
-------

Your Environment
----------------

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/request-yo-racks/infra/issues/19 (Error running bash <(curl -fsSL https://raw.githubusercontent.com/request-yo-racks/infra/master/bootstrap/bootstrap.sh)).

**Comment by chanduvkp** [comment]
This is resolved. Login as admin user using su -, install brew, helm components. exist out from admin user and run make provision configure
