### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by chanduvkp** [request-yo-racks/infra#21]
Getting Page not found (404) for open http://api.192.168.99.100.nip.io/places/

Issue Type
----------
Infra

Expected Behavior
-----------------
API dashboard should open successfully

Current Behavior
----------------
getting 404 page

Possible Solution
-----------------

Steps to Reproduce (for bugs)
-----------------------------
1.Ran below commands
eval $(minikube docker-env)
cd "${RYR_PROJECT_DIR}/api"
make build-docker deploy-minikube

2. open http://api.192.168.99.100.nip.io/places/
3. Getting below error:

Page not found (404)

4.

Context
-------

Your Environment
----------------

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by rgreinho** [comment]
Yep, the doc is wrong. The API requires a `latitude` and a `longitude` as a parameter. I'll update the docs.

**Comment by rgreinho** [comment]
Here is an example of what you can try: http://api.192.168.99.100.nip.io/places/30.318673580117846,-97.72446155548096
