### ISSUE TITLE
Minikube is in an unknown state

### ISSUE THREAD

**Issue by chanduvkp** [request-yo-racks/infra#22]
I am getting below error while running "make provision configure"

**Error**
| => make provision configure
minikube version: v0.25.0
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Minikube is in an unknown state.
Please run 'minikube status' and fix the problem manually.
make[1]: *** [minikube-start] Error 1
make: *** [minikube] Error 2
___________________    | ~/projects/request-yo-racks/infra/kubernetes @ mb032329aus (chandu.venigalla) 
| => minikube status
minikube: Saved
cluster: 
kubectl: 
___________________    | ~/projects/request-yo-racks/infra/kubernetes @ mb032329aus (chandu.venigalla) 
| => make provision configure
minikube version: v0.25.0
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Minikube is in an unknown state.
Please run 'minikube status' and fix the problem manually.
make[1]: *** [minikube-start] Error 1
make: *** [minikube] Error 2

Issue Type
----------
API error

Expected Behavior
-----------------
Getting error below 👍 
| => make provision configure
minikube version: v0.25.0
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Minikube is in an unknown state.
Please run 'minikube status' and fix the problem manually.
make[1]: *** [minikube-start] Error 1
make: *** [minikube] Error 2
___________________    | ~/projects/request-yo-racks/infra/kubernetes @ mb032329aus (chandu.venigalla) 
| => minikube status
minikube: Saved
cluster: 
kubectl: 
___________________    | ~/projects/request-yo-racks/infra/kubernetes @ mb032329aus (chandu.venigalla) 
| => make provision configure
minikube version: v0.25.0
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Minikube is in an unknown state.
Please run 'minikube status' and fix the problem manually.
make[1]: *** [minikube-start] Error 1
make: *** [minikube] Error 2

Current Behavior
----------------

Possible Solution
-----------------

Steps to Reproduce (for bugs)
-----------------------------

1. cd "${RYR_PROJECT_DIR}/infra/kubernetes"
2. make provision configure

Context
-------

Your Environment
----------------

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
MacOS 10.12.6

**Comment by rgreinho** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/request-yo-racks/infra/issues/2 (Set up a minikube environment).

**Comment by rgreinho** [comment]
Running `make unprovision` or `minikube delete` would allow you to reprovision (with `make provision` minikube).
