### ISSUE TITLE
Add logic to either clone or update the project

### ISSUE THREAD

**Issue by ralfredo** [request-yo-racks/infra#28]
Issue Type
----------

- Feature request

Expected Behavior
-----------------

The script snippet that clones the entire project could be enhanced to update the project instead if it already exists.

Current Behavior
----------------

The script snippet clones the project

Possible Solution
-----------------

Add logic to update the project (pull request) rather than to clone it.

Steps to Reproduce (for bugs)
-----------------------------

Here is a piece of code that shows the logic to update the project... it is not yet integrated into the overall script

cd "${RYR_PROJECT_DIR}"
for project in api infra web; do
  cd ${project}
  git pull upstream master
done

Context
-------

Looking to add logic for either clone or update the project depending on whether the project is already present on the local disk or not

Your Environment
----------------

* Version used: N/A
* Browser Name and version: Chrome, Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MAC OS X (desktop) 10.12.6 (16G1314)

**Comment by rgreinho** [comment]
This issue is assigned to @ralfredo.

**Comment by rgreinho** [comment]
Fixed in https://github.com/request-yo-racks/docs/pull/48.
