### ISSUE TITLE
Minikube dashboard never completes

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/infra#59]
Issue Type
----------

- Bug report

Current Behavior
----------------

When the provision script runs `minikube daskboard`, it hangs. This is due to a new behavior in minikube 0.30 to prevent DNS rebinding attacks (ref: https://github.com/kubernetes/minikube/issues/3236).

Expected Behavior
-----------------

Find a command to determine weather the dashboard is up and running. This is used to determine whether minikube is ready to accept requests.

**Comment by sandipsahoo** [comment]
@rgreinho Then how to access the dashboard. Would you please let us know for availability of new command?

**Comment by sandipsahoo** [comment]
Ok. got it. 
The below works.

> kubectl proxy

> http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard:/proxy/#!/overview?namespace=default

**Comment by rgreinho** [comment]
@sandipsahoo if you type `minikube dashboard` in your terminal, the dashboard will popup in your default browser, therefore you can access it that way. 

I do not contribute to the minikube or kubernetes projects so I am not sure if they plan to add a new command.
